name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install and build
        run: |
          npm install
          cd node_modules/base45-ts
          npm run build
          cd ../../functions
          npm ci
          cd ..
          npm run build
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
